### ISSUE TITLE
About Traing code

### ISSUE THREAD

**Issue by Chenngzz** [Flowerfan/VistaLLaMA#1]
In line 19 of vista_llama/train/train_qformer_patch.py, KVReader is imported from dataloader. Has this package been rewritten, or is there any relevant code that you could provide? Thank you very much.

**Comment by Flowerfan** [comment]
The KVreader is for internal use to read the data. You can modify the dataloader function to run the code.

**Comment by dongshenhan** [comment]
I ran into the same issue — have you managed to solve it?
Would you mind sharing the dataloader if possible?
